blank_issues_enabled: false
contact_links:
  - name: Call for Organizers (forum thread)
    url: https://discourse.processing.org/t/pcd-worldwide-2026/48081
    about: Use the forum thread for general questions or discussion about PCD
